# Generated by Django 2.2.12 on 2020-05-06 06:08

from django.db import migrations
import users.managers.user_manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.managers.user_manager.UserManager()),
            ],
        ),
    ]
