# Generated by Django 2.2.12 on 2020-05-01 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('distance', models.PositiveIntegerField()),
                ('time', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Jogs',
                'verbose_name': 'Jog',
            },
        ),
        migrations.CreateModel(
            name='WeatherConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_c', models.IntegerField()),
                ('feels_like_c', models.IntegerField()),
                ('precip_mm', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('cloud_cover', models.PositiveIntegerField()),
                ('weather_desc', models.CharField(max_length=255)),
                ('jog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jogs.Jog')),
            ],
            options={
                'verbose_name_plural': 'Weather Conditions',
                'verbose_name': 'Weather Conditions',
            },
        ),
    ]
