# Generated by Django 2.2.12 on 2020-05-07 06:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jogs', '0002_jogreport'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jogreport',
            unique_together={('user', 'start_date', 'end_date')},
        ),
    ]
