# Generated by Django 2.2.12 on 2020-05-07 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogs', '0003_auto_20200507_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogreport',
            name='avg_distance',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='jogreport',
            name='avg_speed',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
