# Generated by Django 2.2.12 on 2020-05-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogs', '0004_auto_20200507_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
